version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 4000:4000
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/virtual.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_TCP_PORT: 3307
      TZ: "Asia/Tokyo"
    ports:
      - "3307:3306"
    expose:
      - 3307

  app:
    build:
      context: ./docker
    tty: true
    volumes:
      - .:/app
    ports:
      - "3100:3100"
